Repository UCLALibrary/fester, pull requests merged in 2021-04, with the labels that each got.

#177 Update MIME type database so Fester maps .mpd URLs to application/dash+xml
  pom.xml
  src/main/docker/Dockerfile
  src/main/docker/configs/content-types.properties
  src/test/java/edu/ucla/library/iiif/fester/fit/PostCsvFIT.java
  src/test/java/edu/ucla/library/iiif/fester/utils/TestUtils.java
  src/test/resources/csv/video/video_mpd.csv
  src/test/resources/json/v3/video_mpd.json
Labels: bugfix

#176 [IIIF-1143] Update A/V URL Code
  pom.xml
  src/main/docker/configs/fester.properties.default
  src/main/docker/configs/fester.properties.tmpl
  src/main/java/edu/ucla/library/iiif/fester/CSV.java
  src/main/java/edu/ucla/library/iiif/fester/Config.java
  src/main/java/edu/ucla/library/iiif/fester/Constants.java
  src/main/java/edu/ucla/library/iiif/fester/CsvHeaders.java
  src/main/java/edu/ucla/library/iiif/fester/CsvParser.java
  src/main/java/edu/ucla/library/iiif/fester/handlers/PostThumbnailsHandler.java
  src/main/java/edu/ucla/library/iiif/fester/verticles/ManifestVerticle.java
  src/main/java/edu/ucla/library/iiif/fester/verticles/V2ManifestVerticle.java
  src/main/java/edu/ucla/library/iiif/fester/verticles/V3ManifestVerticle.java
  src/main/resources/fester_messages.xml
  src/test/java/edu/ucla/library/iiif/fester/CsvParserTest.java
  src/test/java/edu/ucla/library/iiif/fester/fit/PostCsvFIT.java
  src/test/resources/csv/audio/audio.csv
  src/test/resources/csv/audio/audio_malformed_metadata.csv
  src/test/resources/csv/audio/audio_missing_metadata.csv
  src/test/resources/csv/audio/audio_unneedded_metadata.csv
  src/test/resources/csv/video/video.csv
  src/test/resources/csv/video/video_malformed_metadata.csv
  src/test/resources/csv/video/video_missing_metadata.csv
  src/test/resources/csv/video/video_mpd.csv
  src/test/resources/json/v3/audio.json
  src/test/resources/json/v3/video.json
  src/test/resources/json/v3/video_mpd.json
  src/test/resources/test-config.properties
Labels: bugfix

#180 Add Object Type values to Web documentation
  src/main/webroot/upload/csv/index.html
Labels: documentation

#184 [IIIF-1153] Use icons as Canvas thumbnails for Sound and Video content
  src/main/docker/configs/fester.properties.default
  src/main/docker/configs/fester.properties.tmpl
  src/main/java/edu/ucla/library/iiif/fester/Config.java
  src/main/java/edu/ucla/library/iiif/fester/Constants.java
  src/main/java/edu/ucla/library/iiif/fester/verticles/V3ManifestVerticle.java
  src/test/resources/json/v3/audio.json
  src/test/resources/json/v3/video.json
  src/test/resources/json/v3/video_mpd.json
Labels: feature

#185 Configure Docker container with the Wowza manifest filenames
  pom.xml
  src/main/docker/configs/fester.properties.default
  src/main/docker/configs/fester.properties.tmpl
Labels: bugfix
